export enum AppActions {
  CREATE_FIRST_MEETING = "APP/CREATE_FIRST_MEETING",
  READ_ALL_MEETINGS = "APP/READ_ALL_MEETINGS",
  READ_CACHED_MEETING = "APP/READ_CACHED_MEETING",
  UPDATE_MEETING_CONTRACT_ADDRESS = "APP/UPDATE_MEETING_CONTRACT_ADDRESS",
  UPDATE_MEETING_RSVP_LIST = "APP/UPDATE_MEETING_RSVP_LIST",

  UPDATE_USER_ETHEREUM_ADDRESS = "APP/UPDATE_USER_ETHEREUM_ADDRESS",

  UPDATE_CACHED_MEETING_LOADING = "APP/UPDATE_CACHED_MEETING_LOADING",
}