export enum AppActions {
  ADD_NOTIFICATION = "APP/ADD_NOTIFICATION",
  REMOVE_NOTIFICATION = "APP/REMOVE_NOTIFICATION",

  CREATE_FIRST_MEETING = "APP/CREATE_FIRST_MEETING",
  READ_ALL_MEETINGS = "APP/READ_ALL_MEETINGS",
  READ_CACHED_MEETING = "APP/READ_CACHED_MEETING",
  UPDATE_MEETING_CONTRACT_ADDRESS = "APP/UPDATE_MEETING_CONTRACT_ADDRESS",
  UPDATE_MEETING_RSVP_LIST = "APP/UPDATE_MEETING_RSVP_LIST",
  UPDATE_MEETING_RSVP_LIST_CANCELLATION = "APP/UPDATE_MEETING_RSVP_LIST_CANCELLATION",

  UPDATE_USER_ETHEREUM_ADDRESS = "APP/UPDATE_USER_ETHEREUM_ADDRESS",

  UPDATE_CACHED_MEETING_LOADING = "APP/UPDATE_CACHED_MEETING_LOADING",
  UPDATE_MEETING_DEPLOYMENT_LOADING = "APP/UPDATE_MEETING_DEPLOYMENT_LOADING",
  UPDATE_RSVP_CONFIRMATION_LOADING = "APP/UPDATE_RSVP_CONFIRMATION_LOADING",
  UPDATE_RSVP_CANCELLATION_CONFIRMATION_LOADING = "APP/UPDATE_RSVP_CANCELLATION_CONFIRMATION_LOADING",
}