export enum AppActions {
  CREATE_FIRST_MEETING = "APP/CREATE_FIRST_MEETING",
  READ_ALL_MEETINGS = "APP/READ_ALL_MEETINGS",
  UPDATE_MEETING_CONTRACT_ADDRESS = "APP/UPDATE_MEETING_CONTRACT_ADDRESS",
  UPDATE_MEETING_RSVP_LIST = "APP/UPDATE_MEETING_RSVP_LIST",

  UPDATE_USER_ETHEREUM_ADDRESS = "APP/UPDATE_USER_ETHEREUM_ADDRESS",
}